### ISSUE TITLE
Integration with meteor 2.5 issue

### ISSUE THREAD

**Issue by frankapimenta** [ManuelDeLeon/viewmodel.org#1]
I am trying to upgrade a project from meteor 1.8.x to 2.5 and got stuck in a problem with your excellent library.

```No function 'b'```

<img width="396" alt="Screenshot 2021-12-03 at 23 49 21" src="https://user-images.githubusercontent.com/497761/144682877-c55682fe-4339-4fb8-97e5-024d462516c9.png">

Your library is installed

**Comment by ManuelDeLeon** [comment]
Unfortunately I no longer maintain this library =(
If you submit a PR to https://github.com/ManuelDeLeon/viewmodel I could help you publish it.
